module.exports ={
  PORT:3000,
  SUCCESSCODE:{"200":200,"201":201},
  ERRORCODE:{"400":400,"500":500},
  EMPLOYEE_CREATE_SUCESS:"Employee Added sucessfully",
  EMPLOYEE_CREATE_VALIDATE:"EmployeeId cannot be empty or Invalid request",
  EMPLOYEE_UPDATE_SUCESS:"Employee updated sucessfully",
  EMPLOYEE_DELETE_SUCESS:"Employee deleted sucessfully",
  FILEPATH:"logs/server-%DATE%.log",
  ERROR_FILEPATH:"logs/server.error-%DATE%.log",
  LOGGER_LEVEL_DEBUG:"debug",
  LOGGER_LEVEL_ERROR:"error",
  MAXDAYS:"10d",
  MAXSIZE:"10m",
  DATE:"YYYY-MM-DD",
}